# Generated by Django 4.0.3 on 2022-04-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiryform', '0002_rename_country_city_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiries',
            name='zip_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
