# Generated by Django 4.0.3 on 2022-04-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiryform', '0003_inquiries_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiries',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
